import torch
print(torch.__version__)
scalar=torch.tensor(7)
vector=torch.tensor([7,7])
matrix=torch.tensor([[7,7],[7,7]])
print(scalar)
print(scalar.ndim)
print(scalar.item())
print(vector)
print(vector.ndim)
print(vector.shape)
print(matrix)
print(matrix.ndim)
print(matrix.shape)
