# -*- coding: utf-8 -*-
"""10_28_作業.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1bBFyzOuO06ii8xf-JGviyKfXnHRkDf6R
"""

#第一題
coefsStr=input('輸入:').split()
coefs=[]
for coef in coefsStr:
  coefs.append(float(coef))
coefs.reverse()
params=[]
exp=[]
for i in range(len(coefs),0,-1):
  params.append(float((i-1)*coefs[i-1]))
  exp.append(i-2)
  #儲存係數與次方數
count=0
place=0
print('輸出:',end="")
for param in params:
  if exp[place]==0:
    expStr=""
    #判斷要不要加上x，常數就不用
  else:
    expStr="x^"+str(exp[place])
  if param==0:
    place+=1
    #係數為0，跳過
    continue
  elif param>=0:
    if count!=0:
      #加上+
      print("+"+str(param)+expStr,end="")
    else:
      #第一項，不用加上+
      print(str(param)+expStr,end="")
      count+=1
  elif param<=0:
    #負數，不用加上+
    print(str(param)+expStr,end="")
  place+=1